travis:
  secure:
    BINSTAR_TOKEN: fT5uxwYhqbsxC8bIFWNHcgBYc3exP9hf+6AEl+nVIzN9cTcs520lC4Pk1q74ANmjCWzIHGxOKtsJE0taTrwv1a+VyNpS1UIJgY8IN5QGSoMYKVAZhb9/hVmvkSaGfPJtmiqeI/wTpG4B05+loXQUI80y8jlO6s3fcJeXr2KHNcKO9jEXQ3IkFmc6xBQcNHmbNrB+HET+8MikG/Ys4YNUqhmCsylwhmxsjmzalDs2xe5v9uAcXiEPwCvZfqZmYh5HVoC6I+ScgoQfILR39H+VJSuAX/4ppw4hzWY4kGPbNuTzNxa5zedMzwYPzsQtjht/DFjxXGD0Y7JUb3YAfWQxLCyCD0BNF3WslT59kKSpJB23WPcTuo6sPoenOXX7XRY49du/zyEaU0uTpkVdPBj4zCQ5WcXTYD4cEEmcZyBgSrBozACK+bvTdtsktLg3TZABNfRWd3J2oD9DboK7tLVeI/bM/dZLA69DvzqaUGqIatWgUqGnMS2Rb/sLXtGAvdrDMLBFOup3nNiIzBm49kZy2jCwDm1P1NSZOvE7AMMDyI5OcZQ7mCUbnQe+3R+kV3vL0d9aFYODcRlIQ7gNIHEaMj7NdVmiByMEDRVhaM7i0GddJbDA+6JXE7gv1RV9UfUWfpmKXeNMYLMdKcPHx5Hz1ROSy6tu0pC5UPNnYVBuCN0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
